language: ruby
cache: bundler
script: bundle exec rspec

rvm:
  - 1.9.3
  - "2.0"
  - "2.1"
  - "2.3.0-preview2"
  - rbx-2
  - jruby-19mode
  - ruby-head
  - jruby-head

gemfile:
  - gemfiles/Rails-4.2.gemfile

matrix:
  include:
    - rvm: "2.2"
      gemfile: gemfiles/Rails-4.2.gemfile
      env: RUN_COVERALLS=true

    - rvm: "2.2"
      gemfile: gemfiles/Rails-4.1.gemfile

    - rvm: "2.2"
      gemfile: gemfiles/Rails-4.0.gemfile

    - rvm: "1.9.3"
      gemfile: gemfiles/Rails-3.2.gemfile

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
