language: ruby
cache: bundler
script: bundle exec rspec

rvm:
  - 1.9.3
  - "2.0"
  - "2.1"
  - rbx-2
  - jruby-19mode
  - ruby-head
  - jruby-head

matrix:
  include:
    - rvm: "2.2"
      env: RUN_COVERALLS=true

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
